spring:
  config:
    activate:
      on-profile: develop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{DB_URL}}
    username: root
    password: ${{DB_PASSWORD}}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update